Fixing data as requested in issue #140
ualbertalib/DMPonline_v4 pull request #141
Opened 2017-08-18 19:31 UTC by astrilet

Need to run rake db:seed to commit new change to the database
![screenshot from 2017-08-18 13-25-25](https://user-images.githubusercontent.com/11414991/29474572-78cf82d6-8419-11e7-8683-72e9a1324619.png)

2017-08-18 19:47 UTC, weiweishi requested changes

2017-08-18 19:47 UTC, weiweishi commented on db/seeds.rb
>        exists = true if s.section.to_s == details[:section] && s.section.organisation == details[:organisation]
With how current the data is seeded (checking only the text, and section and their organization), this text change in the guidance will not be picked up. We'd need to change the code here to update guidance for existing questions, or for this fix, change the data in the database directly?

2017-08-22 21:29 UTC, astrilet commented
created new rake task to update data in database
following task needs to be run in the default environment 
rake one_time:datafix_issue140

2017-09-08 21:09 UTC, closed without merging

2017-09-12 16:23 UTC, weiweishi commented
fixed the data through the admin interface.